LANGUAGE_OPTIONS = [
    "Deutsch", "Englisch", "Türkisch", "Arabisch", "Französisch",
    "Spanisch", "Italienisch", "Russisch", "Polnisch", "Weitere Sprache"
]

STUDY_YEAR_OPTIONS = [
    "Vorklinik - 1. Jahr",
    "Vorklinik - 2. Jahr",
    "Klinik - 3. Jahr",
    "Klinik - 4. Jahr",
    "Klinik - 5. Jahr",
    "Praktisches Jahr (PJ)",
    "Promovierend",
    "Anderes"
]

UNIVERSITY_OPTIONS = [
        {"name": "RWTH Aachen", "domain": "@rwth-aachen.de"},
        {"name": "Universität Augsburg", "domain": "@uni-a.de"},
        {"name": "Medical School Berlin – MSB", "domain": "@msb-berlin.de"},
        {"name": "Humboldt-Universität zu Berlin", "domain": "@student.hu-berlin.de"},
        {"name": "Universität Bielefeld", "domain": "@uni-bielefeld.de"},
        {"name": "Ruhr-Universität Bochum", "domain": "@ruhr-uni-bochum.de"},
        {"name": "Friedrich-Wilhelms-Universität Bonn", "domain": "@uni-bonn.de"},
        {"name": "Technische Universität Dresden", "domain": "@tu-dresden.de"},
        {"name": "Heinrich-Heine-Universität Düsseldorf", "domain": "@hhu.de"},
        {"name": "Friedrich-Alexander-Universität Erlangen-Nürnberg", "domain": "@fau.de"},
        {"name": "Universität Duisburg-Essen", "domain": "@uni-due.de"},
        {"name": "Johann-Wolfgang-Goethe-Universität Frankfurt", "domain": "@stud.uni-frankfurt.de"},
        {"name": "Albert-Ludwigs-Universität Freiburg", "domain": "@uni-freiburg.de"},
        {"name": "Justus-Liebig-Universität Gießen", "domain": "@stud.uni-giessen.de"},
        {"name": "Georg-August-Universität Göttingen", "domain": "@stud.uni-goettingen.de"},
        {"name": "Ernst-Moritz-Arndt-Universität Greifswald", "domain": "@uni-greifswald.de"},
        {"name": "Martin-Luther-Universität Halle-Wittenberg", "domain": "@student.uni-halle.de"},
        {"name": "Universität Hamburg", "domain": "@studium.uni-hamburg.de"},
        {"name": "Medizinische Hochschule Hannover", "domain": "@stud.mh-hannover.de"},
        {"name": "Ruprecht-Karls-Universität Heidelberg", "domain": "@stud.uni-heidelberg.de"},
        {"name": "Universität des Saarlandes Homburg", "domain": "@stud.uni-saarland.de"},
        {"name": "Friedrich-Schiller-Universität Jena", "domain": "@uni-jena.de"},
        {"name": "Christian-Albrechts-Universität Kiel", "domain": "@stud.uni-kiel.de"},
        {"name": "Universität Köln", "domain": "@smail.uni-koeln.de"},
        {"name": "Universität Leipzig", "domain": "@studserv.uni-leipzig.de"},
        {"name": "Universität Lübeck", "domain": "@stud.uni-luebeck.de"},
        {"name": "Otto-von-Guericke-Universität Magdeburg", "domain": "@st.ovgu.de"},
        {"name": "Med. Fak. Mannheim (Uni Heidelberg)", "domain": "@stud.uni-heidelberg.de"},
        {"name": "Johannes-Gutenberg-Universität Mainz", "domain": "@students.uni-mainz.de"},
        {"name": "Philipps-Universität Marburg", "domain": "@students.uni-marburg.de"},
        {"name": "Ludwig-Maximilians-Universität München", "domain": "@campus.lmu.de"},
        {"name": "Technische Universität München", "domain": "@tum.de"},
        {"name": "Westfälische Wilhelms-Universität Münster", "domain": "@uni-muenster.de"},
        {"name": "Carl-von-Ossietzky-Universität Oldenburg", "domain": "@uni-oldenburg.de"},
        {"name": "Universität Regensburg", "domain": "@ur.de"},
        {"name": "Universität Rostock", "domain": "@uni-rostock.de"},
        {"name": "Eberhard-Karls-Universität Tübingen", "domain": "@uni-tuebingen.de"},
        {"name": "Universität Ulm", "domain": "@uni-ulm.de"},
        {"name": "Julius-Maximilians-Universität Würzburg", "domain": "@stud-mail.uni-wuerzburg.de"},
        {"name": "Universität Witten/Herdecke", "domain": "@uni-wh.de"},
        {"name": "Medizinische Hochschule Brandenburg", "domain": "@mhb-fontane.de"},
        {"name": "MSH Medical School Hamburg", "domain": "@medicalschool-hamburg.de"},
        {"name": "HMU Health and Medical University", "domain": "@hmu-me.com"},
        {"name": "Paracelsus-Universität Nürnberg", "domain": "@pmu.ac.at"},
        {"name": "Kassel School of Medicine", "domain": "@ksm-mhba.de"},
        {"name": "UMCH Hamburg / Semmelweis Universität", "domain": "@umch.de"},
        {"name": "Andere", "domain": None}
] 

PRAXIS_SKILLS = [
    "Blutentnahme (venös, kapillär)",
    "Venenverweilkanüle legen (PVK)",
    "EKG schreiben",
    "Infusionen vorbereiten / anhängen",
    "Injektionen (s.c., i.m., i.v.)",
    "Verbände",
    "Wundversorgung (einfach)",
    "Vitalzeichenkontrolle (Temperatur, RR, Puls messen)",
    "Blutzuckermessung",
    "Urinstatus durchführen",
    "Katheter legen (männlich/weiblich, unter Anleitung)",
    "OP-Assistenz",
    "Assistenz bei Untersuchungen (z. B. Sonografie, Endoskopie)",
    "Lagerung OP",
    "Vorbereitung von Patientenaufklärung / Einverständniserklärungen",
    "Patientenaufnahme",
    "Anamnese",
    "Ersteinschätzung (ZNA / Triage)",
    "Unterstützung bei klinischen Visiten",
    "Aufnahmeformulare",
    "Krankenhausinformationssystem (KIS)",
    "Arztbriefe",
    "Medikationspläne",
    "Befunde einscannen / zuordnen",
    "Terminvergabe",
    "Diagnoselisten",
    "ICD / OPS-Codierung",
    "Körperpflege",
    "Mobilisation und Lagerung",
    "Hilfe bei der Nahrungsaufnahme",
    "Transfers (z. B. Bett – Stuhl)",
    "Begleitung zu Untersuchungen",
    "Telefonannahme & Weiterleitung",
    "Terminorganisation",
    "Patientenakten",
    "Organisation von Folgeuntersuchungen",
    "Praxissoftware (z. B. Medistar, Turbomed, CGM, Doctolib)",
    "Notaufnahme / ZNA",
    "Hygieneplänen",
    "Umgang mit Schutzkleidung / Isoliermaßnahmen",
    "Impfassistenz / Impfpass-Dokumentation",
    "Studien / Forschung",
    "Digitalen Patientenakten (EPA)",
    "Medizinischer Bildgebung / PACS",
    "MS Office (Word, Excel, Outlook)"
]

INTEREST_FIELDS = [
    "Allgemein-/Viszeralchirurgie",
    "Allgemeinmedizin",
    "Anästhesie",
    "Arbeitsmedizin",
    "Augenheilkunde",
    "Chirurgie",
    "Dermatologie",
    "Digitalisierung",
    "Endokrinologie / Diabetologie",
    "Forschung",
    "Gastroenterologie",
    "Gefäßchirurgie",
    "Geriatrie",
    "Gynäkologie",
    "Hals-Nasen-Ohren-Heilkunde (HNO)",
    "Handchirurgie",
    "Herzchirurgie",
    "Hämatologie / Onkologie",
    "Infektiologie",
    "Innere Medizin",
    "Intensivmedizin",
    "Kardiologie",
    "Kinderchirurgie",
    "Lehre",
    "Medizintechnik",
    "Nephrologie",
    "Neurochirurgie",
    "Neurologie",
    "Notfallmedizin",
    "Nuklearmedizin",
    "Orthopädie",
    "Palliativmedizin",
    "Pathologie",
    "Plastische / Rekonstruktive Chirurgie",
    "Psychiatrie",
    "Psychosomatische Medizin",
    "Pulmologie / Pneumologie",
    "Pädiatrie",
    "Radiologie",
    "Rechtsmedizin",
    "Rheumatologie",
    "Schmerztherapie",
    "Thoraxchirurgie",
    "Unfallchirurgie",
    "Urologie",
    "Verwaltung / Management",
    "Anderes (Freitext)"

]