import streamlit as st
from backend.services.data_service import DataService
from shared.types import HospitalProfile

# Hamburg coordinates for reference
HAMBURG_COORDINATES = {
    "UKE": (53.5897, 9.9756),
    "St. Georg": (53.5553, 10.0114),
    "Barmbek": (53.5869, 10.0406),
    "Altona": (53.5503, 9.9333),
    "Wandsbek": (53.5731, 10.0853),
    "Marienkrankenhaus": (53.5503, 9.9333),
    "Albertinen": (53.5731, 9.9333),
    "Israelitisches": (53.5731, 9.9333)
}

def hospital_form():
    st.header("🏥 Submit Assistantship Position")
    
    with st.form("hospital_form"):
        hospital_name = st.text_input("Hospital Name")
        department = st.text_input("Department")
        title = st.text_input("Position Title")
        description = st.text_area("Description")
        duration = st.text_input("Duration (e.g., 3 months)")
        requirements = st.text_input("Requirements (comma-separated)")
        location = st.text_input("Location")
        stipend = st.text_input("Stipend (optional)")
        
        # Add coordinates selection
        st.markdown("### Standort")
        st.info("Bitte wählen Sie die Klinik aus der Liste oder geben Sie die Koordinaten manuell ein.")
        
        # Hospital selection for coordinates
        selected_hospital = st.selectbox(
            "Klinik auswählen",
            ["Manuelle Eingabe"] + list(HAMBURG_COORDINATES.keys())
        )
        
        if selected_hospital == "Manuelle Eingabe":
            col1, col2 = st.columns(2)
            with col1:
                latitude = st.number_input("Breitengrad", value=53.5503, format="%.4f")
            with col2:
                longitude = st.number_input("Längengrad", value=9.9937, format="%.4f")
        else:
            latitude, longitude = HAMBURG_COORDINATES[selected_hospital]
            st.info(f"Koordinaten für {selected_hospital}: {latitude}, {longitude}")

        submitted = st.form_submit_button("Submit Position")
        if submitted:
            try:
                # Create hospital profile
                hospital = HospitalProfile(
                    id="",  # Will be generated by the service
                    name=hospital_name,
                    department=department,
                    title=title,
                    description=description,
                    duration=duration,
                    requirements=[r.strip() for r in requirements.split(",") if r.strip()],
                    location=location,
                    latitude=latitude,
                    longitude=longitude,
                    stipend=float(stipend) if stipend else None,
                    created_at=None,  # Will be set by the service
                    updated_at=None   # Will be set by the service
                )
                
                # Save using data service
                data_service = DataService()
                saved_hospital = data_service.create_hospital(hospital)
                
                st.success("Position submitted successfully!")
                st.info("Bitte klicken Sie auf 'Aktualisieren' auf der Positionen-Seite, um die neue Position zu sehen.")
                st.balloons()
                
            except Exception as e:
                st.error(f"An error occurred: {str(e)}") 