import streamlit as st
from backend.services.data_service import DataService
from shared.types import HospitalProfile
from shared.categories import MEDICAL_SPECIALTIES, MEDICAL_CERTIFICATIONS

# Hamburg coordinates for reference
HAMBURG_COORDINATES = {
    "UKE": (53.5897, 9.9756),
    "St. Georg": (53.5553, 10.0114),
    "Barmbek": (53.5869, 10.0406),
    "Altona": (53.5503, 9.9333),
    "Wandsbek": (53.5731, 10.0853),
    "Marienkrankenhaus": (53.5503, 9.9333),
    "Albertinen": (53.5731, 9.9333),
    "Israelitisches": (53.5731, 9.9333)
}

def hospital_form():
    st.header("🏥 Submit Assistantship Position")
    
    with st.form("hospital_form"):
        hospital_name = st.text_input("Hospital Name")
        
        # Use selectbox for department
        st.markdown("#### Abteilung")
        st.info("Wählen Sie die Abteilung aus der Liste aus.")
        department = st.selectbox(
            "Abteilung",
            options=MEDICAL_SPECIALTIES,
            help="Wählen Sie die Abteilung für die Position."
        )
        
        title = st.text_input("Positionstitel")
        description = st.text_area("Beschreibung")
        duration = st.text_input("Dauer (z.B. 3 Monate)")
        
        # Use multiselect for requirements
        st.markdown("#### Anforderungen")
        st.info("Wählen Sie die erforderlichen Zertifizierungen aus der Liste aus.")
        requirements = st.multiselect(
            "Anforderungen",
            options=MEDICAL_CERTIFICATIONS,
            help="Wählen Sie die erforderlichen Zertifizierungen für die Position."
        )
        
        location = st.text_input("Standort")
        stipend = st.text_input("Vergütung (optional)")
        
        # Add coordinates selection
        st.markdown("### Standort")
        st.info("Bitte wählen Sie die Klinik aus der Liste oder geben Sie die Koordinaten manuell ein.")
        
        # Hospital selection for coordinates
        selected_hospital = st.selectbox(
            "Klinik auswählen",
            ["Manuelle Eingabe"] + list(HAMBURG_COORDINATES.keys())
        )
        
        if selected_hospital == "Manuelle Eingabe":
            col1, col2 = st.columns(2)
            with col1:
                latitude = st.number_input("Breitengrad", value=53.5503, format="%.4f")
            with col2:
                longitude = st.number_input("Längengrad", value=9.9937, format="%.4f")
        else:
            latitude, longitude = HAMBURG_COORDINATES[selected_hospital]
            st.info(f"Koordinaten für {selected_hospital}: {latitude}, {longitude}")

        submitted = st.form_submit_button("Position hinzufügen")
        if submitted:
            try:
                # Create hospital profile
                hospital = HospitalProfile(
                    id="",  # Will be generated by the service
                    name=hospital_name,
                    department=department,
                    title=title,
                    description=description,
                    duration=duration,
                    requirements=requirements,
                    location=location,
                    latitude=latitude,
                    longitude=longitude,
                    stipend=float(stipend) if stipend else None,
                    created_at=None,  # Will be set by the service
                    updated_at=None   # Will be set by the service
                )
                
                # Save using data service
                data_service = DataService()
                saved_hospital = data_service.create_hospital(hospital)
                
                st.success("Position erfolgreich hinzugefügt!")
                st.info("Bitte klicken Sie auf 'Aktualisieren' auf der Positionen-Seite, um die neue Position zu sehen.")
                st.balloons()
                
            except Exception as e:
                st.error(f"Ein Fehler ist aufgetreten: {str(e)}") 