from backend.services.data_service import DataService
from shared.types import HospitalProfile
from datetime import datetime

# Sample hospital data for Hamburg
SAMPLE_HOSPITALS = [
    {
        "name": "Universitätsklinikum Hamburg-Eppendorf (UKE)",
        "department": "Cardiology",
        "title": "Research Assistant in Cardiology",
        "description": "Support ongoing research in heart failure studies",
        "duration": "3 months",
        "requirements": ["Basic ECG knowledge", "Medical student year 2+"],
        "location": "Martinistraße 52, 20251 Hamburg",
        "latitude": 53.5897,
        "longitude": 9.9756,
        "stipend": 750.0
    },
    {
        "name": "Asklepios Klinik St. Georg",
        "department": "Emergency Medicine",
        "title": "Emergency Department Assistant",
        "description": "Assist in the emergency department during busy hours",
        "duration": "6 months",
        "requirements": ["Basic life support certification", "Medical student year 3+"],
        "location": "Lohmühlenstraße 5, 20099 Hamburg",
        "latitude": 53.5553,
        "longitude": 10.0114,
        "stipend": 800.0
    },
    {
        "name": "Asklepios Klinik Barmbek",
        "department": "Pediatrics",
        "title": "Pediatric Ward Assistant",
        "description": "Support pediatric ward staff in daily activities",
        "duration": "4 months",
        "requirements": ["Experience with children", "Medical student year 2+"],
        "location": "Rübenkamp 220, 22307 Hamburg",
        "latitude": 53.5869,
        "longitude": 10.0406,
        "stipend": 700.0
    }
]

def add_sample_data():
    data_service = DataService()
    
    for hospital_data in SAMPLE_HOSPITALS:
        hospital = HospitalProfile(
            id="",  # Will be generated by service
            created_at=None,  # Will be set by service
            updated_at=None,  # Will be set by service
            **hospital_data
        )
        data_service.create_hospital(hospital)
        print(f"Added position at {hospital.name}")

if __name__ == "__main__":
    add_sample_data() 